---
- name: EDITOR | Include vars for specific os
  ansible.builtin.include_vars: "{{ ansible_distribution | lower }}/main.yml"
  tags:
    - editor
    - vscode
    - nvim

- include_tasks: vscode.yml
  tags:
    - editor
    - vscode

- include_tasks: neovim.yml
  tags:
    - editor
    - nvim
