---
- name: update apt repository cache
  become: True
  ansible.builtin.apt:
    cache_valid_time: 1
    update_cache: true
  register: task_result
  until: task_result is succeeded
  retries: 30
  delay: 10
