---
- name: update grub config
  command: '{{ __grub_update_cmd }}'
  when:
    - auth_security_enable_grub_update | bool
    - grub_update_binary.stat.exists | bool
    - grub_update_binary.stat.executable | bool
  notify:
    - set bootloader file permissions after updating grub config

- name: set bootloader file permissions after updating grub config
  file:
    path: "{{ grub_config_file_boot }}"
    mode: "0644"
