---
- name: ASDF | Include vars for specific os
  ansible.builtin.include_vars: "{{ ansible_distribution | lower }}/main.yml"
  tags:
    - asdf
    - go
    - rust
    - nodejs
    - ruby
    - python

- name: ASDF | Ensure apt packages are managed | Debian
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ __dep_asdf_pkgs }}"
  when: ansible_os_family | lower == 'debian'
  tags:
    - asdf
    - go
    - rust
    - nodejs
    - ruby
    - python

- name: ASDF | Ensure yum packages are managed | Redhat
  become: true
  ansible.builtin.yum:
    name: "{{ packages }}"
    state: "{{ _apt_state }}"
  vars:
    packages: "{{ __dep_asdf_pkgs }}"
    state: '{{ _apt_state | default("present") }}'
  when: ansible_os_family | lower == 'redhat'
  tags:
    - asdf
    - go
    - rust
    - nodejs
    - ruby
    - python

- name: ASDF | Clone asdf
  become: true
  become_user: "{{ user_admin }}"
  ansible.builtin.git:
    repo: "https://github.com/asdf-vm/asdf.git"
    dest: "/home/{{ user_admin }}/.asdf"
    version: "master"
  tags:
    - install
    - asdf
    - go
    - rust
    - nodejs
    - ruby
    - python

- include_tasks: go.yml
  tags:
    - asdf
    - go

- include_tasks: rust.yml
  tags:
    - asdf
    - rust

- include_tasks: nodejs.yml
  tags:
    - asdf
    - nodejs

- include_tasks: ruby.yml
  tags:
    - asdf
    - ruby

- include_tasks: python.yml
  tags:
    - asdf
    - python
