---
- name: ASDF | Include vars for specific os
  ansible.builtin.include_vars: "{{ ansible_distribution | lower }}/main.yml"
  tags:
    - asdf
    - go
    - nodejs
    - python
    - ruby
    - rust
    - zig

- name: "ASDF | Install asdf"
  include_tasks: asdf.yml
  tags:
    - asdf
    - install

- name: "ASDF | Install go with asdf"
  include_tasks: go.yml
  tags:
    - asdf
    - go

- name: "ASDF | Install rust with asdf"
  include_tasks: rust.yml
  tags:
    - asdf
    - rust

- name: "ASDF | Install nodejs with asdf"
  include_tasks: nodejs.yml
  tags:
    - asdf
    - nodejs

- name: "ASDF | Install ruby with asdf"
  include_tasks: ruby.yml
  tags:
    - asdf
    - ruby

- name: "ASDF | Install zig with asdf"
  include_tasks: zig.yml
  tags:
    - asdf
    - zig

- name: "ASDF | Install python with asdf"
  include_tasks: python.yml
  tags:
    - asdf
    - python
