---
- name: ASDF-Nodejs | Include vars for specific os
  ansible.builtin.include_vars: "{{ ansible_distribution | lower }}/main.yml"
  tags:
    - nodejs
    - asdf

- name: ASDF-Nodejs | Check plugin-list if spesific our lang is exists
  become: true
  become_user: "{{ user_admin }}"
  ansible.builtin.shell: |
    source ~/.asdf/asdf.sh && asdf plugin-list
  args:
    executable: /bin/bash
  register: plugin_nodejs_exists
  changed_when: false
  failed_when: false
  ignore_errors: true
  tags:
    - nodejs
    - asdf

# - name: ASDF-Nodejs | Debug plugin_nodejs_exists!
#   ansible.builtin.debug:
#     msg: "{{ plugin_nodejs_exists.stdout.find('nodejs') }}"

- name: ASDF-Nodejs | Install plugin asdf for nodejs
  become: true
  become_user: "{{ user_admin }}"
  ansible.builtin.shell: |
    source ~/.asdf/asdf.sh && {{ nodejs_lang.plugin_asdf_install }}
  args:
    executable: /bin/bash
  changed_when: false
  when:
    # jika plugin sama sekali belum diinstall, masih berupa plugin kosong
    - (plugin_nodejs_exists.stderr.find('No plugins installed') != 0) or (plugin_nodejs_exists.stdout.find('nodejs') == -1)
  tags:
    - nodejs
    - asdf

- name: ASDF-Nodejs | Check nodejs version if exists
  become: true
  become_user: "{{ user_admin }}"
  ansible.builtin.shell: |
    source ~/.asdf/asdf.sh && node --version
  args:
    executable: /bin/bash
  register: nodejs_version_cur_version
  changed_when: false
  failed_when: false
  ignore_errors: true
  tags:
    - nodejs
    - asdf

- name: ASDF-Nodejs | Ensure apt packages are managed | Debian
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ nodejs_lang.plugin_asdf_deps }}"
  when:
    - nodejs_lang.plugin_asdf_deps | length > 0
    - nodejs_version_cur_version.stderr.find(nodejs_version) == -1
    - ansible_os_family | lower == 'debian'
  tags:
    - nodejs
    - asdf

- name: ASDF-Nodejs | Ensure yum packages are managed | Redhat
  become: true
  ansible.builtin.yum:
    name: "{{ item }}"
    state: "{{ _apt_state }}"
  vars:
    state: '{{ _apt_state | default("present") }}'
  with_items:
    - "{{ nodejs_lang.plugin_asdf_deps }}"
  when:
    - nodejs_lang.plugin_asdf_deps | length > 0
    - nodejs_version_cur_version.stderr.find(nodejs_version) == -1
    - ansible_os_family | lower == 'redhat'
  tags:
    - nodejs
    - asdf

- name: ASDF-Nodejs | Install nodejs version
  become: true
  become_user: "{{ user_admin }}"
  ansible.builtin.shell: |
    source ~/.asdf/asdf.sh && asdf install nodejs {{ nodejs_lang.plugin_asdf_nodejs_version }}
  args:
    executable: /bin/bash
  changed_when: false
  register: nodejs_version_installed
  when:
    - nodejs_version_cur_version.stderr.find(nodejs_version) == -1
  tags:
    - nodejs
    - asdf

- name: ASDF-Nodejs | Ensure global version are defined
  become: true
  become_user: "{{ user_admin }}"
  ansible.builtin.shell: |
    source ~/.asdf/asdf.sh && {{ nodejs_lang.plugin_asdf_set_global_version }}
  args:
    executable: /bin/bash
  changed_when: false
  when:
    - nodejs_version_installed is success
  tags:
    - nodejs
    - asdf
