---
- name: ASDF-Python | Check plugin-list if spesific our lang is exists
  become: true
  become_user: "{{ user_admin }}"
  ansible.builtin.shell: |
    /home/{{ user_admin }}/.local/bin/asdf list python
  args:
    executable: /bin/bash
  register: plugin_python_exists
  changed_when: false
  failed_when: false
  ignore_errors: true
  tags:
    - asdf
    - python

# - name: ASDF-Python | Debug plugin_python_exists!
#   ansible.builtin.debug:
#     msg: "{{ plugin_python_exists }}"

- name: ASDF-Python | Install asdf plugin for python
  become: true
  become_user: "{{ user_admin }}"
  ansible.builtin.shell: |
    /home/{{ user_admin }}/.local/bin/asdf {{ item.plugin_asdf_install }}
  args:
    executable: /bin/bash
  changed_when: false
  with_items:
    - "{{ python_lang.0 }}"
  when:
    - plugin_python_exists.stderr | length > 0
  tags:
    - asdf
    - python

- name: ASDF-Python | Check version python2 python3 version
  become: true
  become_user: "{{ user_admin }}"
  ansible.builtin.shell: |
    {{ item.plugin_asdf_name }} --version
  args:
    executable: /bin/bash
  environment:
    PATH: "/home/{{ user_admin }}/.asdf/shims:{{ lookup('env', 'PATH') }}"
  register: "python_version_cur_version"
  changed_when: false
  failed_when: false
  loop: "{{ python_lang | flatten(levels=1) }}"
  ignore_errors: true
  tags:
    - asdf
    - python

# - name: ASDF-Python | Debug python_version_cur_version!
#   ansible.builtin.debug:
#     msg: "{{ python_version_cur_version }}"

# - name: ASDF-Python | Debug python_version_cur_version!
#   ansible.builtin.debug:
#     msg: "{{ item.stderr }}"
#   with_items:
#     - "{{ python_version_cur_version.results }}"

- name: ASDF-Python | Set fact python_versions
  ansible.builtin.set_fact:
    python_versions: "{{ [ item ]  }}"
  when:
    - item.stderr | length > 0
    - item.stderr.find('command not found') != -1
  with_items:
    - "{{ python_version_cur_version.results }}"
  tags:
    - asdf
    - python

# - name: ASDF-Python | Debug python_versions!
#   ansible.builtin.debug:
#     msg: "{{ python_versions }}"
#   when: python_versions is defined
#   tags:
#     - asdf
#     - python

- block:
    - name: ASDF-Python | Ensure apt packages are managed | Debian
      become: true
      ansible.builtin.apt:
        name: "{{ item.plugin_asdf_deps }}"
        state: present
      with_items:
        - "{{ python_lang | flatten(levels=1) }}"
      when:
        - item.plugin_asdf_deps | length > 0
        - ansible_os_family | lower == 'debian'
      tags:
        - asdf
        - python

    - name: ASDF-Python | Ensure yum packages are managed | Redhat
      become: true
      ansible.builtin.yum:
        name: "{{ item.plugin_asdf_deps }}"
        state: present
      with_items:
        - "{{ python_lang | flatten(levels=1) }}"
      when:
        - item.plugin_asdf_deps | length > 0
        - ansible_os_family | lower == 'redhat'
      tags:
        - asdf
        - python

    - name: ASDF-Python | Install both python2 and python3 version
      become: true
      become_user: "{{ user_admin }}"
      ansible.builtin.shell: |
        /home/{{ user_admin }}/.local/bin/asdf install python {{ item.plugin_asdf_version }}
      args:
        executable: /bin/bash
      changed_when: false
      register: python_version_installed
      with_items:
        - "{{ python_lang | flatten(levels=1) }}"
      tags:
        - asdf
        - python

    - name: ASDF-Python | Set global for python version on .tool_version
      become: true
      become_user: "{{ user_admin }}"
      ansible.builtin.shell: |
        /home/{{ user_admin }}/.local/bin/asdf set --home python {{ python_lang.0.plugin_asdf_version }} {{ python_lang.1.plugin_asdf_version }}
      args:
        executable: /bin/bash
      changed_when: false
      environment:
        PATH: "/home/{{ user_admin }}/.local/bin:{{ lookup('env', 'PATH') }}"
      when:
        - python_version_installed is success
      tags:
        - asdf
        - python
  when:
    - python_versions is defined
    - python_versions | length > 0
  tags:
    - asdf
    - python
