---
- name: ASDF-Zig | Check plugin-list if spesific our lang is exists
  become: true
  become_user: "{{ user_admin }}"
  ansible.builtin.shell: |
    /home/{{ user_admin }}/.local/bin/asdf list zig
  args:
    executable: /bin/bash
  register: plugin_zig_exists
  changed_when: false
  failed_when: false
  ignore_errors: true
  tags:
    - asdf
    - zig

# - name: ASDF-Zig | Debug plugin_zig_exists!
#   ansible.builtin.debug:
#     msg: "{{ plugin_zig_exists.stdout.find('zig') }}"

- name: ASDF-Zig | Install plugin asdf for zig
  become: true
  become_user: "{{ user_admin }}"
  ansible.builtin.shell: |
    /home/{{ user_admin }}/.local/bin/asdf {{ zig_lang.plugin_asdf_install }}
  args:
    executable: /bin/bash
  changed_when: false
  when:
    - plugin_zig_exists.stderr | length > 0
  tags:
    - asdf
    - zig

- name: ASDF-Zig | Check zig version if exists
  become: true
  become_user: "{{ user_admin }}"
  ansible.builtin.shell: |
    zig version
  args:
    executable: /bin/bash
  environment:
    PATH: "/home/{{ user_admin }}/.asdf/shims:{{ lookup('env', 'PATH') }}"
  register: zig_version_cur_version
  changed_when: false
  failed_when: false
  ignore_errors: true
  tags:
    - asdf
    - zig

# - name: ASDF-Zig | Debug zig_version_cur_version
#   ansible.builtin.debug:
#     msg: "{{ zig_version_cur_version }}"

- block:
    - name: ASDF-Zig | Ensure apt packages are managed | Debian
      become: true
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      with_items:
        - "{{ zig_lang.plugin_asdf_deps }}"
      when:
        - zig_lang.plugin_asdf_deps | length > 0
        - ansible_os_family | lower == 'debian'
      tags:
        - asdf
        - zig

    - name: ASDF-Zig | Ensure yum packages are managed | Redhat
      become: true
      ansible.builtin.yum:
        name: "{{ item }}"
        state: "{{ _apt_state }}"
      vars:
        state: '{{ _apt_state | default("present") }}'
      with_items:
        - "{{ zig_lang.plugin_asdf_deps }}"
      when:
        - zig_lang.plugin_asdf_deps | length > 0
        - ansible_os_family | lower == 'redhat'
      tags:
        - asdf
        - zig

    - name: ASDF-Zig | Install zig version
      become: true
      become_user: "{{ user_admin }}"
      ansible.builtin.shell: |
        /home/{{ user_admin }}/.local/bin/asdf install zig {{ zig_lang.plugin_asdf_zig_version }}
      args:
        executable: /bin/bash
      changed_when: false
      register: zig_version_installed
      environment:
        PATH: "/home/{{ user_admin }}/.local/bin:{{ lookup('env', 'PATH') }}"
      tags:
        - asdf
        - zig

    - name: ASDF-Zig | Set global for zig version on .tool_version
      become: true
      become_user: "{{ user_admin }}"
      ansible.builtin.shell: |
        /home/{{ user_admin }}/.local/bin/asdf set --home zig {{ zig_lang.plugin_asdf_zig_version}}
      args:
        executable: /bin/bash
      changed_when: false
      register: zig_version_installed
      environment:
        PATH: "/home/{{ user_admin }}/.local/bin:{{ lookup('env', 'PATH') }}"
      when:
        - zig_version_installed is success
      tags:
        - asdf
        - zig
  when:
    - zig_version_cur_version.stderr | length > 0
  tags:
    - asdf
    - zig
