---
- name: DOCKER | Check docker if exis
  become: true
  become_user: "{{ user_admin }}"
  ansible.builtin.shell: |
    set -o pipefail;
    if command -v docker &> /dev/null;
    then docker --version | cut -d" " -f3 | cut -d"," -f1 ; else echo "not found"; fi
  args:
    chdir: "/home/{{ user_admin }}"
    executable: /bin/bash
  changed_when: false
  register: check_docker_version

- name: DOCKER | Install docker dep
  ansible.builtin.include_role:
    name: _0package
  vars:
    _apt_packages: "{{ __docker_dep }}"
  when: docker_version not in check_docker_version.stdout
  tags:
    - install
    - docker

- name: DOCKER | Ensure docker repo is present
  ansible.builtin.include_role:
    name: _0package
    tasks_from: ppa
  vars:
    apt_repo_keys:
      - "{{ docker_apt_key }}"
    apt_repo_repositories:
      - "{{ docker_apt_repo }}"
  when: docker_version not in check_docker_version.stdout
  tags:
    - install
    - docker

- name: DOCKER | Install docker dep
  ansible.builtin.include_role:
    name: _0package
  vars:
    _apt_packages: "{{ [docker_package_name] }}"
  when: docker_version not in check_docker_version.stdout
  tags:
    - install
    - docker

- name: DOCKER | Ensure user is added to docker group
  become: true
  ansible.builtin.user:
    name: "{{ user_admin }}"
    groups: docker
    append: yes
    update_password: on_create
  when: docker_version not in check_docker_version.stdout
  tags:
    - install
    - docker
