---
- name: VIRTUALMANAGER | Include vars for specific os
  ansible.builtin.include_vars: "{{ ansible_distribution | lower }}/main.yml"
  tags:
    - always

- name: VIRTUALMANAGER | Start install virtualmanager
  become: true
  block:
    - name: Import task docker.yml
      ansible.builtin.import_tasks: docker.yml
    - name: Import task docker_compose.yml
      ansible.builtin.import_tasks: docker_compose.yml

    # Alternative virualbox?
    # for test jangan di docker di vm saja
    - name: Import task qemu.yml
      ansible.builtin.import_tasks: qemu.yml
