---
- name: DOCKER | Check docker if exis
  become: true
  become_user: "{{ user_admin }}"
  ansible.builtin.shell: |
    set -o pipefail;
    if command -v docker &> /dev/null;
    then docker --version | cut -d" " -f3 | cut -d"," -f1 ; else echo "not found"; fi
  args:
    chdir: "/home/{{ user_admin }}"
    executable: /bin/bash
  changed_when: false
  register: check_docker_version
  tags:
    - install
    - docker
