---
- name: WM LOCK | Include vars for specific os
  ansible.builtin.include_vars: "{{ ansible_distribution | lower }}/main.yml"
  tags:
    - wm-lock

- name: WM LOCK | Debug wm lock
  ansible.builtin.debug:
    msg: "{{ temp_dir }}"
  tags:
    - wm-lock

- name: WM LOCK | Check command i3lock if exists
  ansible.builtin.shell: |
    if command -v i3lock &> /dev/null;
    then echo "found"; else echo "not found"; fi
  args:
    executable: /bin/bash
  changed_when: false
  register: check_i3lock_color_command
  tags:
    - wm-lock

- name: WM LOCK | Install i3lock if not exists
  when: check_i3lock_color_command.stdout.find('not found') != -1
  tags:
    - wm-lock
  block:
    - name: WM LOCK | Install dependencies i3lock
      ansible.builtin.include_role:
        name: _0package
      vars:
        _apt_packages: "{{ __wm_i3lock_color_deps }}"
      tags:
        - install
        - wm-lock

    - name: WM LOCK | Clone i3lock
      git:
        repo: "https://github.com/Raymo111/i3lock-color.git"
        dest: "{{ temp_dir }}/i3lock-color"
        update: yes
        version: master
      register: jobi3lockcolordownload
      until: jobi3lockcolordownload is succeeded
      retries: 10
      delay: 10
      tags:
        - install
        - wm-lock

    - name: WM LOCK | Install i3lock
      ansible.builtin.shell: |
        ./install-i3lock-color.sh
      args:
        chdir: "{{ temp_dir }}/i3lock-color"
        executable: /bin/bash
      changed_when: false
      tags:
        - wm-lock

- name: WM LOCK | Check command betterlockscreen if exists
  ansible.builtin.shell: |
    if command -v betterlockscreen &> /dev/null;
    then echo "found"; else echo "not found"; fi
  args:
    executable: /bin/bash
  changed_when: false
  register: check_betterlockscreen_command
  tags:
    - wm-lock

- name: WM LOCK | Install betterlockscreen if not exists
  when: check_betterlockscreen_command.stdout.find('not found') != -1
  tags:
    - wm-lock
  block:
    - name: WM LOCK | Install dependencies betterlockscreen
      ansible.builtin.include_role:
        name: _0package
      vars:
        _apt_packages: "{{ __wm_betterlockscreen_deps }}"
      tags:
        - wm-lock

    - name: WM_LCOK | Clone betterlockscreen
      git:
        repo: "https://github.com/betterlockscreen/betterlockscreen.git"
        dest: "{{ temp_dir }}/betterlockscreen"
        update: yes
        version: next
      register: jobbetterlockscreendownload
      until: jobbetterlockscreendownload is succeeded
      retries: 10
      delay: 10
      tags:
        - wm-lock

    - name: WM LOCK | Install betterlockscreen
      ansible.builtin.shell: |
        ./install.sh system
      args:
        chdir: "{{ temp_dir }}/betterlockscreen"
        executable: /bin/bash
      changed_when: false
      tags:
        - wm-lock
