---
# defaults file for prolang

python3_version: "{{ _install_programming.python3.python3_version }}"
python2_version: "{{ _install_programming.python3.python2_version }}"

rust_version: "{{ _install_programming.rust.rust_version }}"
nodejs_version: "{{ _install_programming.nodejs.nodejs_version }}"
ruby_version: "{{ _install_programming.ruby.ruby_version }}"
go_version: "{{ _install_programming.golang.golang_version }}"
lua_version: "{{ _install_programming.lua.lua_version }}"

install_prolangs:
  - lang_name: "python2"
    lang_deps: "{{ __dep_python_pkgs }}"
    lang_version: "{{ python2_version}}"
    lang_plugin_asdf_name: "python"
    lang_plugin_install: |
      asdf plugin-add python
    lang_cmd_check_version: |
      if command -v python2 &> /dev/null;
      then python2 --version ; else echo "not found"; fi
    lang_set_global_version: |
      asdf global python {{ python2_version }}

  - lang_name: "python3"
    lang_deps: "{{ __dep_python_pkgs }}"
    lang_version: "{{ python3_version }}"
    lang_plugin_asdf_name: "python"
    lang_plugin_install: |
      asdf plugin-add python
    lang_cmd_check_version: |
      if command -v python &> /dev/null;
      then python --version ; else echo "not found"; fi
    lang_set_global_version: |
      asdf global python {{ python3_version }} {{ python2_version }}

  - lang_name: "rust"
    lang_deps: []
    lang_version: "{{ rust_version }}"
    lang_plugin_asdf_name: "rust"
    lang_plugin_install: |
      asdf plugin-add rust https://github.com/code-lever/asdf-rust.git
    lang_cmd_check_version: |
      if command -v rustc &> /dev/null;
      then rustc --version ; else echo "not found"; fi
    lang_set_global_version: |
      asdf global rust {{ rust_version }}

  - lang_name: "nodejs"
    lang_deps: "{{ __dep_nodejs_pkgs }}"
    lang_version: "{{ nodejs_version }}"
    lang_plugin_asdf_name: "nodejs"
    lang_plugin_install: |
      asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
    lang_cmd_check_version: |
      if command -v node &> /dev/null;
      then node --version ; else echo "not found"; fi
    # lang_cmd_install_plugin: |
    #    asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
    lang_set_global_version: |
      asdf global nodejs {{ nodejs_version }}

  - lang_name: "ruby"
    lang_deps: []
    lang_version: "{{ ruby_version }}"
    lang_plugin_asdf_name: "ruby"
    lang_plugin_install: |
      asdf plugin add ruby https://github.com/asdf-vm/asdf-ruby.git
    lang_cmd_check_version: |
      if command -v ruby &> /dev/null;
      then ruby --version ; else echo "not found"; fi
    lang_set_global_version: |
      asdf global ruby {{ ruby_version }}

  - lang_name: "golang"
    lang_deps: []
    lang_version: "{{ go_version }}"
    lang_plugin_asdf_name: "golang"
    lang_plugin_install: |
      asdf plugin-add golang https://github.com/kennyp/asdf-golang.git
    lang_cmd_check_version: |
      if command -v go &> /dev/null;
      then go version ; else echo "not found"; fi
    lang_set_global_version: |
      asdf global golang {{ go_version }}

  - lang_name: "lua"
    lang_deps: "{{ __dep_lua_pkgs }}"
    lang_version: "{{ lua_version }}"
    lang_plugin_asdf_name: "lua"
    lang_plugin_install: |
      asdf plugin-add lua https://github.com/Stratus3D/asdf-lua.git
    lang_cmd_check_version: |
      if command -v lua &> /dev/null;
      then lua -v ; else echo "not found"; fi
    lang_set_global_version: |
      asdf global lua {{ lua_version }}
