---
#>python.yml ==================================================================
__dep_pkgs:
  - build-essential
  - git
  - make
  - g++
  - gcc
  - cmake
  - make
  - libssl-dev
  - zlib1g-dev
  - libbz2-dev
  - libreadline-dev
  - libsqlite3-dev
  - llvm
  - libncursesw5-dev
  - xz-utils
  - tk-dev
  - libxml2-dev
  - libxmlsec1-dev
  - libffi-dev
  - liblzma-dev
  - curl
  - wget

#>nodejs.yml ==================================================================
__dep_nodejs_pkgs:
  - gpg
  - curl
  - dirmngr
  - gawk
