---
- name: DUNST | Include vars for specific os
  ansible.builtin.include_vars: "{{ ansible_distribution | lower }}/main.yml"
  tags:
    - dunst

- name: DUNST | Check dunst installed version
  ansible.builtin.shell: >
    if command -v dunst &> /dev/null;
    then dunst --version; else echo "not found"; fi
  args:
    executable: /bin/bash
  changed_when: false
  register: check_dunst_version
  tags:
    - dunst

# - name: Test debug
#   debug:
#     msg: "{{ check_dunst_version.stdout.find(dunst_version) }}"
#   when: dunst_version not in check_dunst_version.stdout or check_dunst_version.stdout.find('not found') != -1

# - name: Test Pause
#   pause:
#     seconds: 10

- name: DUNST
  become: true
  when: dunst_version not in check_dunst_version.stdout or check_dunst_version.stdout.find('not found') != -1
  block:
    - name: DUNST | Remove old dunst
      ansible.builtin.apt:
        name: dunst
        state: absent
      tags:
        - install
        - dunst

    - name: DUNST | Ensure apt packages are managed | Debian
      become: true
      ansible.builtin.apt:
        name: "{{ __dunst_deps }}"
        state: present
      when: ansible_os_family | lower == 'debian'
      tags:
        - install
        - dunst

    - name: DUNST | Ensure tmp dir to hold any temporary files for dunst
      ansible.builtin.tempfile:
        state: directory
        suffix: build
      register: temp_dir_dunst
      changed_when: false
      tags:
        - install
        - dunst

    - name: DUNST | Download dunst tar .gz
      ansible.builtin.get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }}"
        mode: 0755
        force: True
        timeout: 30
      register: jobdunstdownload
      until: jobdunstdownload is succeeded
      retries: 10
      delay: 10
      become: true
      with_items:
        - "{{ dunst_download }}"
      tags:
        - install
        - dunst

    - name: DUNST | Extract dunst tar .gz
      ansible.builtin.unarchive:
        src: "{{ item.dest }}/{{ item.name }}.tar.gz"
        dest: "{{ item.dest }}"
        copy: no # with no will not copy or will deleted
      with_items: "{{ dunst_download }}"
      tags:
        - install
        - dunst

    - name: DUNST | Install dunst
      ansible.builtin.shell: |
        make && sudo make install
      args:
        chdir: "{{ item.dest }}/{{ item.name }}"
      changed_when: false
      with_items:
        - "{{ dunst_download }}"
      tags:
        - install
        - dunst
