---
- name: FOLDERS | Create folders
  become: yes
  become_user: "{{ user_admin }}"
  file:
    state: directory
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ default_folders }}"
  tags:
    - always
    - install
