---
- name: Environment | Include vars for specific os
  include_vars: "{{ ansible_distribution | lower }}/main.yml"
  tags:
    - always

- become: yes
  block:
    - name: USERS | Check for .shosts or shosts.equiv files
      find:
        paths: /
        recurse: yes
        hidden: yes
        patterns: ".shosts,shosts.equiv"
      changed_when: False
      register: shosts_find
      async: 300
      poll: 0
      when:
        # - not check_mode | bool
        - _run_auth_security_remove_shosts_files | bool
      tags:
        - high
        - auth

    - name: Importing task accounts
      import_tasks: accounts.yml
    - name: Importing task auth
      import_tasks: auth.yml
    - name: Importing task create
      import_tasks: create.yml
    - name: Importing task visido
      import_tasks: visudo.yml
    - name: Importing task folders
      import_tasks: folders.yml
    - name: Importing task dotfiles
      import_tasks: dotfiles.yml
    - name: Importing task lolcale
      import_tasks: locale.yml
