---
- name: INIT | Get the username running the deploy
  become: false
  delegate_to: localhost
  command: whoami
  register: username_on_the_host
  changed_when: false

- name: INIT | Set_fact user_admin
  set_fact:
    user_admin: "{{ username_on_the_host.stdout_lines[0] }}"
  when: username_on_the_host is defined

- name: INIT | Create tmp dir to hold any temporary files
  tempfile:
    state: directory
    suffix: build
  register: mktemp_result
  changed_when: false
  tags:
    - always

- name: INIT | Set_fact temp dir path
  set_fact:
    temp_dir: "{{ mktemp_result.path }}"
  changed_when: False
  tags:
    - always

- block:
    - name: INIT | Yum Update | Redhat
      yum:
        name: "*"
        state: latest
      when: ansible_distribution | lower == 'centos'
      tags:
        - install
        - updatesync
        - skip_ansible_lint

    - name: INIT | Remove apt source.list | Debian
      file:
        state: absent
        path: "/etc/apt/sources.list"
      changed_when: false
      when:
        - ansible_os_family | lower == 'debian'
        - ansible_distribution_major_version == "9"
      tags:
        - install

    - name: INIT | Upload new source_list for | Debian
      template:
        src: "{{ ansible_distribution | lower }}/{{ ansible_distribution_major_version }}/source.list.j2"
        dest: "/etc/apt/sources.list"
        owner: "root"
        group: "root"
        mode: "0644"
      changed_when: false
      when:
        - ansible_os_family | lower == 'debian'
      tags:
        - install

    - name: INIT | Apt update | Debian
      apt:
        upgrade: dist
        update-cache: yes
        cache_valid_time: 3200
      changed_when: 0
      when: ansible_os_family | lower == 'debian'
      tags:
        - always
        - install
        - updatesync

    - name: INIT | Installing pre-reqs
      include_role:
        name: _0package
      vars:
        _apt_packages:
          ["build-essential", "software-properties-common", "gpg-agent"]
      tags:
        - always
        - install

      when: ansible_os_family | lower == 'debian'

  when: _dev_mode | bool
