---
- name: Tools | Include vars for specific os
  ansible.builtin.include_vars: "{{ ansible_distribution | lower }}/main.yml"
  tags:
    - always

- name: Tools | Inclue task base.yml
  ansible.builtin.include_tasks: base.yml

- name: Tools | Include task misc.yml
  ansible.builtin.include_tasks: misc.yml
