---
- name: Tools | Include vars for specific os
  ansible.builtin.include_vars: "{{ ansible_distribution | lower }}/main.yml"
  tags:
    - always

- include_tasks: base.yml
- include_tasks: misc.yml
