---
- name: Tools | Include vars for specific os
  ansible.builtin.include_vars: "{{ ansible_distribution | lower }}/main.yml"
  tags:
    - always

- name: Tools | Import task base.yml
  ansible.builtin.import_tasks: base.yml

- name: Tools | Import task misc.yml
  ansible.builtin.import_tasks: misc.yml
