---
- name: DUNST | Check dunst installed version
  shell: >
    if command -v dunst &> /dev/null;
    then dunst --version; else echo "not found"; fi
  args:
    warn: no
    executable: /bin/bash
  changed_when: false
  register: check_dunst_version
  tags:
    - always

# - name: Test debug
#   debug:
#     msg: "{{ check_dunst_version.stdout.find(dunst_version) }}"
#   when: dunst_version not in check_dunst_version.stdout or check_dunst_version.stdout.find('not found') != -1

# - name: Test Pause
#   pause:
#     seconds: 10

- become: True
  block:
    - name: DUNST | Remove old dunst
      apt:
        name: dunst
        state: absent
      tags:
        - install
        - dunst

    - name: DUNST | Install dependencies dunst
      include_role:
        name: _0package
      vars:
        _apt_packages: "{{ __dunst_deps }}"
      tags:
        - install
        - dunst

    - name: DUNST | Ensure path {{ temp_dir }}/dunst are exists
      file:
        path: "{{ temp_dir }}/{{ item }}"
        state: directory
        mode: "0755"
      with_items:
        - dunst
      tags:
        - install
        - dunst

    - name: DUNST | Download dunst-{{ dunst_version }}.tar.gz
      get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }}"
        mode: 0755
        force: True
        timeout: 30
      register: jobdunstdownload
      until: jobdunstdownload is succeeded
      retries: 10
      delay: 10
      become: True
      with_items:
        - "{{ dunst_download }}"
      tags:
        - install
        - dunst

    - name: DUNST | Extract dunst-{{ dunst_version }}.tar.gz
      unarchive:
        src: "{{ item.dest }}/{{ item.name }}.tar.gz"
        dest: "{{ item.dest }}"
        copy: no # with no will not copy or will deleted
      with_items: "{{ dunst_download }}"

    - name: DUNST | Install dunst
      shell: |
        make && sudo make install
      args:
        chdir: "{{ item.dest }}/{{ item.name }}"
      with_items:
        - "{{ dunst_download }}"
      tags:
        - install
        - tmux
  when: dunst_version not in check_dunst_version.stdout or check_dunst_version.stdout.find('not found') != -1
