- name: PICOM | Check picom installed version
  shell: >
    if command -v picom &> /dev/null;
    then picom --version; else echo "not found"; fi
  args:
    warn: no
    executable: /bin/bash
  changed_when: false
  register: check_picom_version
  tags:
    - always

- become: True
  block:
    - name: PICOM | Remove old picom
      apt:
        name: picom
        state: absent
      tags:
        - install
        - picom

    - name: PICOM | Install dependencies picom
      include_role:
        name: _0package
      vars:
        _apt_packages: "{{ __picom_deps }}"
      tags:
        - install
        - picom

    - name: PICOM | Ensure path {{ temp_dir }}/picom are exists
      file:
        path: "{{ temp_dir }}/{{ item }}"
        mode: "0755"
        state: directory
      with_items:
        - picom
      tags:
        - install
        - picom

    - name: PICOM | Clone picom with submodule
      git:
        repo: "https://github.com/ibhagwan/picom.git"
        dest: "{{ temp_dir }}/picom"
        recursive: yes
        update: yes
        version: next-rebase
      register: jobpicomdownload
      until: jobpicomdownload is succeeded
      retries: 10
      delay: 10
      become: True
      tags:
        - install
        - picom

    - name: PICOM | Install picom
      shell: |
        meson --buildtype=release . build
        ninja -C build
        sudo ninja -C build install
      args:
        chdir: "{{ temp_dir }}/picom"
      tags:
        - install
        - picom
  when: check_picom_version.stdout.find('not found') != -1
