# polybar
- name: POLYBAR | Check polybar installed version
  shell: >
    set -o pipefail;
    if command -v polybar &> /dev/null;
    then polybar --version | cut -d" " -f2 | head -1 ; else echo "not found"; fi
  args:
    warn: no
    executable: /bin/bash
  changed_when: false
  register: check_polybar_version
  tags:
    - always

- become: true
  block:
    - name: POLYBAR | Install polybar deps
      include_role:
        name: _0package
      vars:
        _apt_packages: "{{ __polybar_deps }}"
      tags:
        - install
        - polybar

    - name: POLYBAR | Ensure polybar folder temp exists
      file:
        path: "{{ temp_dir }}/polybar"
        state: directory
      tags:
        - install
        - polybar

    - name: POLYBAR | Download polybar-{{ polybar_version }}.tar.gz
      become: true
      get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }}"
        mode: 0755
        force: True
        timeout: 30
      register: jobpolybardownload
      until: jobpolybardownload is succeeded
      retries: 10
      delay: 10
      with_items: "{{ polybar_download }}"
      tags:
        - install
        - polybar

    - name: POLYBAR | Extract polybar-{{ polybar_version }}.tar.gz
      unarchive:
        src: "{{ item.dest }}/{{ item.name }}.tar.gz"
        dest: "{{ item.dest }}"
        copy: no # with no will not copy or will deleted
      with_items: "{{ polybar_download }}"

    - name: POLYBAR | Install polybar
      shell: |
        mkdir build
        cd build
        cmake ..
        make -j$(nproc)
        sudo make install
      args:
        warn: no
        chdir: "{{ item.dest }}/{{ item.name }}"
        executable: /bin/bash
      with_items: "{{ polybar_download }}"
      tags:
        - install
        - polybar
  when: polybar_version not in check_polybar_version.stdout or check_polybar_version.stdout.find('not found') != -1
