---
- become: yes
  block:
    - name: BSPWM | Ensure bspwm dependencies installed
      include_role:
        name: _0package
      vars:
        _apt_packages: "{{ __bspwm_deps }}"
      tags:
        - install
        - bspwm

    - name: BSPWM | Ensure file bspwm {{ temp_dir }} exists
      file:
        path: "{{ temp_dir }}/{{ item }}"
        state: directory
      with_items:
        - bspwm
        - sxhkd
        - sutils
        - xtitle
        - xdo
      tags:
        - install
        - bspwm

    - name: BSPWM | Clone bspwm from github
      git:
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
        clone: yes
        update: no
        force: yes
        recursive: false
      retries: 3
      delay: 3
      register: bspwmdlgit
      until: bspwmdlgit is success
      with_items:
        - "{{ bspwm_git }}"
      tags:
        - install
        - bspwm

    - name: BSPWM | Install bspwm
      shell: |
        make
        make install
      args:
        executable: /bin/bash
        chdir: "{{ temp_dir }}/{{ item }}"
      with_items:
        - bspwm
        - sxhkd
        - sutils
        - xtitle
        - xdo
      tags:
        - install
        - bspwm

    - name: BSPWM | Copy bspwm-session to /usr/bin
      shell: |
        cp contrib/freedesktop/bspwm.desktop /usr/share/xsessions
      args:
        executable: /bin/bash
        chdir: "{{ temp_dir }}/{{ item }}"
      with_items:
        - bspwm
        # - xdo
      tags:
        - install
        - bspwm

    - name: BSPWM | Ensure file executable bspwmrc perm 0755
      file:
        path: "/home/{{ user_admin }}/.config/bspwm/bspwmrc"
        owner: "{{ user_admin }}"
        group: "{{ user_admin }}"
        mode: 0755
      tags:
        - install
        - bspwm
