---
- name: Environment | Include vars for specific os
  include_vars: "{{ ansible_distribution | lower }}/main.yml"
  tags:
    - always

- become: yes
  block:
    - import_tasks: bspwm.yml
    - import_tasks: awesome.yml
    - import_tasks: dwm.yml
    - import_tasks: wm_tools.yml
  when: ansible_os_family | lower == 'debian'
