---
- name: Environment | Include vars for specific os
  ansible.builtin.include_vars: "{{ ansible_distribution | lower }}/main.yml"
  tags:
    - always

- name: Testing bro
  become: true
  when: ansible_os_family | lower == 'debian'
  block:
    # WM VARIAN ---------------------------------------------------------------
    - name: Import task bspwm.yml
      ansible.builtin.import_tasks: bspwm.yml
    # - import_tasks: awesome.yml
    # - import_tasks: dwm.yml

    # WM Tools ----------------------------------------------------------------
    - name: Import task _dunst.yml
      ansible.builtin.import_tasks: _dunst.yml
    - name: Import task _polybar.yml
      ansible.builtin.import_tasks: _polybar.yml
    - name: Import task _oomox.yml
      ansible.builtin.import_tasks: _oomox.yml
    - name: Import task _wm_lock.yml
      ansible.builtin.import_tasks: _wm_lock.yml
