---
- name: Environment | Include vars for specific os
  include_vars: "{{ ansible_distribution | lower }}/main.yml"
  tags:
    - always

- become: True
  block:
    # WM VARIAN
    - import_tasks: bspwm.yml
    # - import_tasks: awesome.yml
    # - import_tasks: dwm.yml

    # WM Tools
    - import_tasks: _dunst.yml
    - import_tasks: _picom.yml
    - import_tasks: _polybar.yml
    - import_tasks: _rofi.yml
    - import_tasks: _oomox.yml
  when: ansible_os_family | lower == 'debian'
