# dunst
- name: DUNST | Check dunst installed version
  shell: >
    if command -v dunst &> /dev/null;
    then dunst --version; else echo "not found"; fi
  args:
    warn: no
    executable: /bin/bash
  changed_when: false
  register: check_dunst_version
  tags:
    - always

# - name: Test debug
#   debug:
#     msg: "{{ check_dunst_version.stdout.find(dunst_version) }}"
#   when: dunst_version not in check_dunst_version.stdout or check_dunst_version.stdout.find('not found') != -1

# - name: Test Pause
#   pause:
#     seconds: 10

- become: yes
  block:
    - name: DUNST | Remove old dunst
      apt:
        name: dunst
        state: absent
      tags:
        - install
        - dunst

    - name: DUNST | Install dependencies dunst
      include_role:
        name: _0package
      vars:
        _apt_packages: "{{ __dunst_deps }}"
      tags:
        - install
        - dunst

    - name: DUNST | Ensure path {{ temp_dir }}/dunst are exists
      file:
        path: "{{ temp_dir }}/{{ item }}"
        state: directory
      with_items:
        - dunst
      tags:
        - install
        - dunst

    - name: DUNST | Download dunst-{{ dunst_version }}.tar.gz
      get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }}"
        mode: 0755
        force: True
        timeout: 30
      register: jobdunstdownload
      until: jobdunstdownload is succeeded
      retries: 10
      delay: 10
      become: True
      with_items:
        - "{{ dunst_download }}"
      tags:
        - install
        - dunst

    - name: DUNST | Extract dunst-{{ dunst_version }}.tar.gz
      unarchive:
        src: "{{ item.dest }}/{{ item.name }}.tar.gz"
        dest: "{{ item.dest }}"
        copy: no # with no will not copy or will deleted
      with_items: "{{ dunst_download }}"

    - name: DUNST | Install dunst
      shell: |
        make && sudo make install
      args:
        chdir: "{{ item.dest }}/{{ item.name }}"
      with_items:
        - "{{ dunst_download }}"
      tags:
        - install
        - tmux
  when: dunst_version not in check_dunst_version.stdout or check_dunst_version.stdout.find('not found') != -1

# rofi
- name: ROFI | Check rofi installed version
  shell: >
    set -o pipefail;
    if command -v rofi &> /dev/null;
    then rofi -V | cut -d":" -f2 | cut -d" " -f2 |xargs ; else echo "not found"; fi
  args:
    warn: no
    executable: /bin/bash
  changed_when: false
  register: check_rofi_version
  tags:
    - always

- become: yes
  block:
    - name: ROFI | Ensure rofi folder temp exists
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ temp_dir }}/rofi"
        - "{{ temp_dir }}/check"
      tags:
        - install
        - rofi

    - name: ROFI | Install build dependencies for rofi
      include_role:
        name: _0package
      vars:
        _apt_packages: "{{ __rofi_deps }}"
      tags:
        - install
        - rofi

    - name: DUNST | Download rofi-{{ rofi_version }}.tar.gz
      become: yes
      get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }}"
        mode: 0755
        force: True
        timeout: 30
      register: jobrofidownload
      until: jobrofidownload is succeeded
      retries: 10
      delay: 10
      with_items: "{{ rofi_download }}"
      tags:
        - install
        - rofi

    - name: RODI | Extract rofi-{{ rofi_version }}.tar.gz
      unarchive:
        src: "{{ item.dest }}/{{ item.name }}.tar.gz"
        dest: "{{ item.dest }}"
        copy: no # with no will not copy or will deleted
      with_items: "{{ rofi_download }}"

    - name: ROFI | Install rofi
      shell: |
        ./configure --disable-check && make && sudo make install
      args:
        warn: no
        chdir: "{{ item.dest }}/{{ item.name }}"
        executable: /bin/bash
      with_items: "{{ rofi_download }}"
      tags:
        - install
        - rofi
  when: rofi_version not in check_rofi_version.stdout or check_rofi_version.stdout.find('not found') != -1

# polybar
- name: POLYBAR | Check polybar installed version
  shell: >
    set -o pipefail;
    if command -v polybar &> /dev/null;
    then polybar --version | cut -d" " -f2 | head -1 ; else echo "not found"; fi
  args:
    warn: no
    executable: /bin/bash
  changed_when: false
  register: check_polybar_version
  tags:
    - always

- become: yes
  block:
    - name: POLYBAR | Install polybar deps
      include_role:
        name: _0package
      vars:
        _apt_packages: "{{ __polybar_deps }}"
      tags:
        - install
        - polybar

    - name: POLYBAR | Ensure polybar folder temp exists
      file:
        path: "{{ temp_dir }}/polybar"
        state: directory
      tags:
        - install
        - polybar

    - name: POLYBAR | Download polybar-{{ polybar_version }}.tar.gz
      become: yes
      get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }}"
        mode: 0755
        force: True
        timeout: 30
      register: jobpolybardownload
      until: jobpolybardownload is succeeded
      retries: 10
      delay: 10
      with_items: "{{ polybar_download }}"
      tags:
        - install
        - polybar

    - name: POLYBAR | Extract polybar-{{ polybar_version }}.tar.gz
      unarchive:
        src: "{{ item.dest }}/{{ item.name }}.tar.gz"
        dest: "{{ item.dest }}"
        copy: no # with no will not copy or will deleted
      with_items: "{{ polybar_download }}"

    - name: POLYBAR | Install polybar
      shell: |
        mkdir build
        cd build
        cmake ..
        make -j$(nproc)
        sudo make install
      args:
        warn: no
        chdir: "{{ item.dest }}/{{ item.name }}"
        executable: /bin/bash
      with_items: "{{ polybar_download }}"
      tags:
        - install
        - polybar
  when: polybar_version not in check_polybar_version.stdout or check_polybar_version.stdout.find('not found') != -1
