---
__dunst_deps:
  - dbus-x11
  - libdbus-1-dev
  - libx11-dev
  - libxinerama-dev
  - libxrandr-dev
  - libxss-dev
  - libglib2.0-dev
  - libpango1.0-dev
  - libgtk-3-dev
  - libxdg-basedir-dev
  - libnotify-dev
  - libnotify-bin
