---
- name: Converge
  hosts: all
  tasks:
    - name: "Include my init"
      include_role:
        name: "_init"
    - name: "Include environment"
      include_role:
        name: "environment"
    # - name: "Include prolang"
    #   include_role:
    #     name: "prolang"
    - name: "Include tools"
      include_role:
        name: "tools"
