---
- name: Converge
  hosts: all
  tasks:
    - name: "Include my init"
      ansible.builtin.include_role:
        name: "_init"
    - name: "Include environment"
      ansible.builtin.include_role:
        name: "environment"
    - name: "Include prolang"
      ansible.builtin.include_role:
        name: "prolang"
    - name: "Include tools"
      ansible.builtin.include_role:
        name: "tools"
