---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  # - name: centos7
  #   image: "percygrunwald/docker-centos7-ansible:latest"
  #   command: ""
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   privileged: true
  #   pre_build_image: true
  # - name: ubuntu1804
  #   image: "percygrunwald/docker-ubuntu1804-ansible:latest"
  #   command: ""
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   privileged: true
  #   pre_build_image: true
  # - name: debian9
  #   image: "percygrunwald/docker-debian9-ansible:latest"
  #   command: ""
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   privileged: true
  #   pre_build_image: true

  - name: debian11
    image: "debian:bullseye"

    # command: ""
    # volumes:
    #   - /sys/fs/cgroup:/sys/fs/cgroup:ro
    # privileged: true
    # pre_build_image: true
  - name: ubuntu2004
    image: "ubuntu:20.04"
    # command: ""
    # volumes:
    #   - /sys/fs/cgroup:/sys/fs/cgroup:ro
    # privileged: true
    # pre_build_image: true

provisioner:
  name: ansible
  config_options:
    defaults:
      timeout: 60
      stdout_callback: yaml
      bin_ansible_callbacks: True
      interpreter_python: auto_silent
      callback_enabled: profile_tasks, timer, yaml
      remote_tmp: /tmp/${USER}/ansible
    ssh_connection:
      pipelining: True
      ssh_args: -C -o ControlMaster=auto -o ControlPersist=60s -o IdentitiesOnly=yes -o PreferredAuthentications=publickey
      retries: 3
  # https://molecule.readthedocs.io/en/stable/configuration.html#id22
  # targeting group_vars global
  inventory:
    links:
      group_vars: ../../../../group_vars/
  # st terminal no color output, to solve this we need this env to force it
  # https://www.jeffgeerling.com/blog/2020/getting-colorized-output-molecule-and-ansible-on-github-actions-ci
  env:
    PY_COLORS: "1"
    ANSIBLE_FORCE_COLOR: "1"
    ANSIBLE_ROLES_PATH: "../../../_init"
verifier:
  name: ansible

# ansible-lint -c ../../.ansible-lint
lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8 .
scenario:
  name: default # optional
  create_sequence:
    - create
    - prepare
  check_sequence:
    - destroy
    - dependency
    - create
