---
__picom_deps:
  - dbus-devel
  - gcc
  - git
  - libconfig-devel
  - libdrm-devel
  - libev-devel
  - libX11-devel
  - libX11-xcb
  - libXext-devel
  - libxcb-devel
  - libGL-devel
  - libEGL-devel
  - libepoxy-devel
  - meson pcre2-devel
  - pixman-devel
  - uthash-devel
  - xcb-util-image-devel
  - xcb-util-renderutil-devel
  - xorg-x11-proto-devel
  - xcb-util-devel
