- name: TOOLSPROGRAM | Install tools via apt
  include_role:
    name: _0package
  vars:
    _apt_packages: "{{ item.pkg_lists }}"
  when: item.pkg_install_with == "apt"

- name: TOOLSPROGRAM | Set fact for join string
  set_fact:
    pkg_lists_to_install: "{{ pkg_lists_to_install | default([]) + [ ' '.join((item.pkg_shell_install, mypkgs ))] }}"
  loop: "{{ item.pkg_lists }}"
  loop_control:
    loop_var: mypkgs
  when: item.pkg_install_with == "asdf"

- name: TOOLSPROGRAM | Install tools {{ item.pkg_name }} via asdf
  become: True
  become_user: "{{ user_admin }}"
  shell: |
    source ~/.asdf/asdf.sh && {{ pkg_install }}
  args:
    executable: /bin/bash
  changed_when: False
  loop: "{{ pkg_lists_to_install }}"
  loop_control:
    loop_var: pkg_install
  register: pkg_asdf_installed
  when: item.pkg_install_with == "asdf"

- name: TOOLSPROGRAM | Reshim the plugin {{ item.pkg_name }}
  become: True
  become_user: "{{ user_admin }}"
  shell: |
    source ~/.asdf/asdf.sh && asdf reshim {{ item.pkg_name }}
  args:
    executable: /bin/bash
  changed_when: False
  when:
    - item.pkg_install_with == "asdf"
    - pkg_asdf_installed is success
