---
- name: 00PACKAGE | Ensure apt packages are managed | Debian
  become: True
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    autoclean: yes
    autoremove: yes
    force_apt_get: yes
    update_cache: yes
    # cache_valid_time: 50000
    install_recommends: False
  retries: 5
  delay: 5
  register: jobcommon
  until: jobcommon is success
  vars:
    packages: "{{ _apt_packages }}"
    state: '{{ _apt_state | default("present") }}'
  when: ansible_os_family | lower == 'debian'
  tags:
    - always

- name: 00PACKAGE | Ensure yum packages are managed | Redhat
  ansible.builtin.yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages: "{{ _apt_packages }}"
    state: '{{ _apt_state | default("present") }}'
  become: True
  when: ansible_os_family | lower == 'redhat'
  tags:
    - always
