---
- name: Converge
  hosts: all
  tasks:
    - name: "Include _init"
      include_role:
        name: "_init"
    - name: "Include environment"
      include_role:
        name: "environment"
    - name: "Include tool-docker"
      include_role:
        name: "tool-docker"
