---
- name: DISABLE-FIREWALLD | Check if firewalld package is installed | Redhat
  command: yum list installed firewalld
  args:
    warn: no
  register: firewalld_installed
  ignore_errors: true
  failed_when: false
  changed_when: false
  when:
    - ansible_os_family | lower == 'redhat'
  tags:
    - install
    - iptables

- name: DISABLE-FIREWALLD | Disable the firewalld service | Redhat
  service:
    name: firewalld
    state: stopped
    enabled: no
  when:
    - ansible_os_family | lower == 'redhat'
    - disabled_firewall_firewalld
    - firewalld_installed.rc == 0
  tags:
    - install
    - iptables

- name: DISABLE-FIREWALLD | Checking ufw yang masih aktif | Debian
  command: service ufw status
  args:
    warn: no
  register: ufw_isactive
  ignore_errors: true
  failed_when: false
  changed_when: false
  when:
    - ansible_distribution | lower == 'debian'
  tags:
    - install
    - iptables

- name: DISABLE-FIREWALLD | Disable service ufw | Debian
  service:
    name: ufw
    state: stopped
    enabled: no
  when:
    - ansible_distribution | lower == 'debian'
    - disabled_firewall_ufw
    - ufw_isactive.rc == 0
  tags:
    - install
    - iptables
