---
- name: Tools | Include vars for specific os
  ansible.builtin.include_vars: "{{ ansible_distribution | lower }}/main.yml"
  tags:
    - always

- name: Install iptables and disable firewalld
  become: true
  block:
    - name: Import iptables.yml
      ansible.builtin.import_tasks: iptables.yml
    - name: Import disable-firewalld.yml
      ansible.builtin.import_tasks: disable-firewalld.yml
