---
- name: Tools | Include vars for specific os
  include_vars: "{{ ansible_distribution | lower }}/main.yml"
  tags:
    - always

- become: True
  block:
    - import_tasks: iptables.yml
    - import_tasks: disable-firewalld.yml
