---
#>python.yml ==================================================================
__dep_pkgs:
  - "@Development Tools"
  - gcc
  - zlib-devel
  - bzip2
  - bzip2-devel
  - readline-devel
  - sqlite
  - sqlite-devel
  - openssl-devel
  - tk-devel
  - libffi-devel
  - xz-devel
  - curl
  - wget

#>nodejs.yml ==================================================================
__dep_nodejs_pkgs:
  - gpg
  - curl
