---
- name: MISC | Include vars for specific os
  ansible.builtin.include_vars: "{{ ansible_distribution | lower }}/main.yml"
  tags:
    - misc
    - mpdris
    - pamixer
    - folders
    - dropbox
    - tools

- include_tasks: mpdris2-rs.yml
  tags:
    - misc
    - mpdris
# - include_tasks: pamixer.yml
#   tags:
#     - misc
#     - pamixer

- include_tasks: folders.yml
  tags:
    - misc
    - folders

- include_tasks: dropbox.yml
  tags:
    - misc
    - folders

- include_tasks: tools.yml
  tags:
    - misc
    - tools

- include_tasks: autoenv.yml
  tags:
    - misc
    - autoenv
