__mpv_deps:
  # - debhelper (>= 7)
  # - libdav1d-dev
  - autoconf
  - automake
  - build-essential
  - gcc
  - ladspa-sdk
  - libarchive-dev
  - libasound2-dev
  - libass-dev
  - libavcodec-dev
  - libavfilter-dev
  - libavformat-dev
  - libavutil-dev
  - libbluray-dev
  - libbrotli-dev
  - libbs2b-dev
  - libcaca-dev
  - libcdio-paranoia-dev
  - libdrm-dev
  - libdvdnav-dev
  - libegl1-mesa-dev
  - libfontconfig-dev
  - libfreetype6-dev
  - libfribidi-dev
  - libgbm-dev
  - libgl1-mesa-dev
  - libgme-dev
  - libgnutls28-dev
  # - libgpac-dev
  - libgsm1-dev
  - libharfbuzz-dev
  - libjack-dev
  - libjpeg-dev
  - liblcms2-dev
  - liblircclient-dev
  - liblua5.1-0-dev
  - libmodplug-dev
  - libmp3lame-dev
  - libopenal-dev
  - libopencore-amrnb-dev
  - libopencore-amrwb-dev
  - libopus-dev
  - libpulse-dev
  - librtmp-dev
  - librubberband-dev
  - libsdl1.2-dev
  - libsoxr-dev
  - libspeex-dev
  - libssh-dev
  - libswresample-dev
  - libtag1-dev
  - libtheora-dev
  - libtool
  - libuchardet-dev
  - libv4l-dev
  - libva-dev
  - libvdpau-dev
  - libvo-amrwbenc-dev
  - libvorbis-dev
  - libvpx-dev
  - libwayland-dev
  - libx11-dev
  - libx264-dev
  - libxext-dev
  - libxinerama-dev
  - libxkbcommon-dev
  - libxrandr-dev
  - libxss-dev
  - libxv-dev
  - libxvidcore-dev
  - nasm
  - pkg-config
  - python3
  - python3-docutils
  - texi2html
  - x11proto-core-dev
  - yasm
  - zlib1g-dev
