---
#>docker.yml ==================================================================
docker_channel: ["stable"]

docker_package_name: docker-ce
docker_version: "{{ _install_tooling.docker.docker_version }}"

docker_apt_key:
  url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
  id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"

docker_apt_repo:
  file: docker
  repo: |
    deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_channel | join (" ") }}

#>docker_compose.yml ==========================================================
docker_compose_version: "{{ _install_tooling.docker.docker_compose_version }}"
docker_compose_repo_format: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}"
