---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu_12_04
    image: ubuntu:22.04
  - name: debian_12_5
    image: debian:12.5
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    links:
      group_vars: ../../../../group_vars/
  options:
    vvv: true
  env:
    ANSIBLE_ROLES_PATH: ../../../../roles/
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8 .
scenario:
  name: default # optional
  create_sequence:
    - create
    - prepare
  check_sequence:
    - destroy
    - dependency
    - create
