---
# lua_version: "5.4.7"
lua_version: "5.1"

build_from_source_lua:
  - pkg_name: "lua"
    pkg_version: "{{ lua_version }}"
    pkg_cmd_check_version: |
      bash -lc 'if command -v lua &> /dev/null;
      then lua -v ; else echo "not found"; fi'
    link:
      - url: "https://www.lua.org/ftp/lua-{{ lua_version }}.tar.gz"
        tar_file: "lua-{{ lua_version }}.tar.gz"
        dest_tar_file: "lua-{{ lua_version }}"
    pkg_cmd_make: |
      make linux && sudo make install

luarocks_version: "3.11.1"

build_from_source_luarocks:
  - pkg_name: "luarocks"
    pkg_version: "{{ luarocks_version }}"
    pkg_cmd_check_version: |
      bash -lc 'if command -v luarocks &> /dev/null;
      then luarocks --version ; else echo "not found"; fi'
    link:
      - url: "https://luarocks.org/releases/luarocks-{{ luarocks_version }}.tar.gz"
        tar_file: "luarocks-{{ luarocks_version }}.tar.gz"
        dest_tar_file: "luarocks-{{ luarocks_version }}"
    pkg_cmd_make: |
      sudo ./configure && make && sudo make install

fonts_jetbrains_mono_version: "2.304"
fonts_jetbrains_mono_version_nerd_fonts: "2.3.3"
fonts_hack_nerd_font_version: "3.4.0"
fonts_maple_mono_version: "7.5"

fonts_extract_to: "/tmp/extracted-fonts"
fonts_install_path: "~/.local/share/fonts"
fonts_archive_pattern: "*.zip"
fonts_git:
  - repo: "https://github.com/supercomputra/SF-Mono-Font"
    version: "master"
    dest: "{{ fonts_install_path }}/sf-mono"
  - repo: "https://github.com/zapolnoch/CousinsHug"
    version: "main"
    dest: "{{ fonts_install_path }}/cousinshug"

fonts_wget:
  - url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v{{ fonts_jetbrains_mono_version_nerd_fonts }}/JetBrainsMono.zip"
    dest: "{{ fonts_install_path }}"
  - url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v{{ fonts_hack_nerd_font_version }}/Hack.zip"
    dest: "{{ fonts_install_path }}"
  - url: "https://github.com/subframe7536/maple-font/releases/download/v{{ fonts_maple_mono_version }}/MapleMonoNL-NF.zip"
    dest: "{{ fonts_install_path }}"
