---
# tasks file for browsers
- name: BROWSERS | Include vars for specific os
  ansible.builtin.include_vars: "{{ ansible_distribution | lower }}/main.yml"
  tags:
    - always

- name: BROWSERS | Fasdf
  ansible.builtin.include_vars: ""
  become: true
  block:
    - name: Import task firefox.yml
      ansible.builtin.import_tasks: firefox.yml
