---
- name: ALACRITTY | Check alacritty path if exists
  stat:
    path: "/home/{{ user_admin }}/.asdf/shims/alacritty"
  register: check_alacritty_path
  tags:
    - always

- block:
    - name: ALACRITTY | Install alacritty deps
      include_role:
        name: _0package
      vars:
        _apt_packages: "{{ __alacritty_pkg }}"
      tags:
        - install
        - nvim

    - name: ALACRITTY | Install alacritty with cargo
      become: yes
      become_user: "{{ user_admin }}"
      shell: |
        source ~/.asdf/asdf.sh && cargo install alacritty
      args:
        executable: /bin/bash
      register: installed_alacritty

    - name: ALACRITTY | Reshim rust after install alacritty
      become: yes
      become_user: "{{ user_admin }}"
      shell: |
        source ~/.asdf/asdf.sh && asdf reshim rust
      args:
        warn: no
        executable: /bin/bash
      when: installed_alacritty is success
  when: not check_alacritty_path.stat.exists
