---
- name: FZF | Check folder .fzf if exists
  become: true
  become_user: "{{ user_admin }}"
  ansible.builtin.stat:
    path: "/home/{{ user_admin }}/.fzf"
  register: check_fzf
  tags:
    - always

- name: Run if FZF home path not exists
  become: true
  when: not check_fzf.stat.exists
  block:
    - name: FZF | Git Clone FZF ke home user
      become: true
      become_user: "{{ user_admin }}"
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        dest: "/home/{{ user_admin }}/{{ item.name }}"
        version: "{{ item.version }}"
        accept_hostkey: yes
        force: yes
      with_items:
        - "{{ fzf_repo }}"
      tags:
        - install
        - fzf

    - name: FZF | Install FZF
      become: true
      become_user: "{{ user_admin }}"
      ansible.builtin.command: |
        /home/{{ user_admin }}/.fzf/install
      register: fzf_install
      changed_when: false
      tags:
        - install
        - fzf

    - name: FZF | Set permisson folder.FZF di homedir
      become: true
      become_user: "{{ user_admin }}"
      ansible.builtin.file:
        path: "/home/{{ user_admin }}/.fzf"
        owner: "{{ user_admin }}"
        group: "{{ user_admin }}"
        recurse: "yes"
      when: fzf_install is success
      tags:
        - install
        - fzf
