---
- name: UPDATE | Apt-get update | Debian
  apt:
    upgrade: dist
    update-cache: yes
    cache_valid_time: 3200
  changed_when: 0
  when: ansible_os_family | lower == 'debian'
  tags:
    - always
    - install
    - updatesync

- name: Installing pre-reqs
  include_role:
    name: _0package
  vars:
    _apt_packages: "{{ __base_pkg }}"
  tags:
    - always
    - install

- name: Installing tools
  include_role:
    name: _0package
  vars:
    _apt_packages: "{{ __tools + __tools_extensions }}"
  when: __tools | length > 0 and __tools_extensions | length > 0
  tags:
    - install
