---
- name: TOOLS | Include vars for specific os
  ansible.builtin.include_vars: "{{ ansible_distribution | lower }}/main.yml"
  tags:
    - always

- name: TOOLS asfd
  become: true
  when: ansible_os_family | lower == 'debian'
  block:
   # - name: TOOLS | Install tools from build source
   #   ansible.builtin.include_role:
   #     name: _0package
   #     tasks_from: buildsource
   #   with_items: "{{ install_tools_from_buildsource }}"

   # - name: TOOLS | Install tools with asdf source with lang
   #   ansible.builtin.include_role:
   #     name: _0package
   #     tasks_from: installwithasdf
   #   with_items: "{{ install_tools_from_asdf }}"

   # - name: TOOLS | Install tools with build from source git
   #   ansible.builtin.include_role:
   #     name: _0package
   #     tasks_from: buildsourcewithgit
   #   with_items: "{{ install_tools_from_git }}"

   # - name: Import task folders.yml
   #   ansible.builtin.import_tasks: folders.yml
   # - name: Import task autoenv.yml
   #   ansible.builtin.import_tasks: autoenv.yml
   # - name: Import task dropbox.yml
   #   ansible.builtin.import_tasks: dropbox.yml
   # - name: Import task neovim.yml
   #   ansible.builtin.import_tasks: neovim.yml
    - name: Import task alacritty.yml
      ansible.builtin.import_tasks: alacritty.yml
    - name: Import task kitty.yml
      ansible.builtin.import_tasks: kitty.yml
    # - name: Import task vscode.yml
    #   ansible.builtin.import_tasks: vscode.yml
    - name: Import task maim_slop.yml
      ansible.builtin.import_tasks: maim_slop.yml
   # - name: Import task mpv.yml
   #   ansible.builtin.import_tasks: mpv.yml
    - name: Import task tools.yml
      ansible.builtin.import_tasks: tools.yml
   # - name: Import task task.yml
   #   ansible.builtin.import_tasks: fzf.yml
   # - name: Import task zsh.yml
   #   ansible.builtin.import_tasks: zsh.yml
