---
- name: TOOLS | Include vars for specific os
  ansible.builtin.include_vars: "{{ ansible_distribution | lower }}/main.yml"
  tags:
    - always

- name: TOOLS asfd
  become: true
  when: ansible_os_family | lower == 'debian'
  block:
    # - name: TOOLS | Install tools from build source
    #   ansible.builtin.include_role:
    #     name: _0package
    #     tasks_from: buildsource
    #   with_items: "{{ install_tools_from_buildsource }}"

    # - name: TOOLS | Install tools with asdf source with lang
    #   ansible.builtin.include_role:
    #     name: _0package
    #     tasks_from: installwithasdf
    #   with_items: "{{ install_tools_from_asdf }}"

    # - name: TOOLS | Install tools with build from source git
    #   ansible.builtin.include_role:
    #     name: _0package
    #     tasks_from: buildsourcewithgit
    #   with_items: "{{ install_tools_from_git }}"

    # - name: Import task folders.yml
    #   ansible.builtin.import_tasks: folders.yml
    # - name: Import task autoenv.yml
    #   ansible.builtin.import_tasks: autoenv.yml
    # - name: Import task dropbox.yml
    #   ansible.builtin.import_tasks: dropbox.yml
    - name: Import task tools.yml
      ansible.builtin.import_tasks: tools.yml
