---
- name: Tools | Include vars for specific os
  include_vars: "{{ ansible_distribution | lower }}/main.yml"
  tags:
    - always

- become: yes
  block:
    - import_tasks: tools.yml
    # - import_tasks: tools_programming.yml
    # - import_tasks: tmux.yml
    - import_tasks: telegram.yml
