---
# Untuk install mpv butuh dependencies
- name: MPV | Clone mpv-build from github
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    clone: yes
    update: no
    force: yes
    version: master
    recursive: false
  retries: 3
  delay: 3
  register: mpvdlgit
  until: mpvdlgit is success
  with_items: "{{ mpv_build }}"

- name: MPV | Ensure mpv deps installed
  include_role:
    name: _0package
  vars:
    _apt_packages: "{{ __mpv_deps }}"

- name: MPV | Install MPV
  shell: |
    printf "%s\n" --disable-gl > mpv_options
    ./rebuild -j4
    sudo ./install
  args:
    executable: /bin/bash
    chdir: "{{ item.dest }}"
  when: mpvdlgit is success
  with_items: "{{ mpv_build }}"
