- name: TELEGRAM | Checking telegram install on the system
  shell: >
    bash -lc 'if command -v telegram &> /dev/null;
    then echo "found" else echo "not found"; fi'
  register: telegram_check
  changed_when: false
  tags:
    - always

- become: yes
  block:
    - name: TELEGRAM | Install telegram deps
      include_role:
        name: _0package-meta
      vars:
        _apt_packages: "{{ __telegram_deps }}"
      tags:
        - install
        - telegram

    - name: TELEGRAM | Ensure path {{ temp_dir }}/telegram are exists
      file:
        path: "{{ temp_dir }}/telegram"
        state: directory
      tags:
        - install
        - telegram

    - name: TELEGRAM | Download telegram {{ telegram_version }}.tar.xz
      get_url:
        url: "{{ telegram_link_download }}"
        dest: "{{ temp_dir }}/telegram"
      register: download_telegram
      tags:
        - install
        - telegram

    - name: TELEGRAM | Unarchive tar telegram then move to /opt/telegram
      shell: >
        bash -lc 'tar -xf tsetup.*.*.*.tar.xz &&
        mv Telegram /opt'
      args:
        chdir: "{{ temp_dir }}/telegram"
      when: download_telegram is success
      tags:
        - install
        - telegram

    - name: TELEGRAM | Set symlink bin telegram /opt/telegram to /usr/local/bin/telegram
      file:
        src: "/opt/Telegram/Telegram"
        dest: "/usr/local/bin/telegram"
        state: link
      tags:
        - install
        - telegram

  when: telegram_check.stdout.find('not found') == -1
