---
- name: VSCODE | Install vscode deps
  ansible.builtin.include_role:
    name: _0package
  vars:
    _apt_packages: "{{ __vscode_shared_dep }}"
  tags:
    - install
    - vscode

- name: VSCODE | Ensure vscode repo is present
  ansible.builtin.include_role:
    name: _0package
    tasks_from: ppa
  vars:
    apt_repo_keys:
      - "{{ vscode_apt_key }}"
    apt_repo_repositories:
      - "{{ vscode_apt_repo }}"
  tags:
    - install
    - vscode

- name: VSCODE | Install vscode (apt)
  ansible.builtin.include_role:
    name: _0package
  vars:
    _apt_packages: '{{ visual_studio_code_package }}{{ (visual_studio_code_version | length > 0) | ternary("=" + visual_studio_code_version, "") }}'
  tags:
    - install
    - vscode
