---
##############################
#
# WM VARIAN
#
##############################
#
# }}}
# AWESOME --------------------------------------------------------- {{{
awesome_git:
  - repo: "https://github.com/awesomewm/awesome"
    dest: "{{ temp_dir }}/awesome"
  - repo: "https://github.com/baskerville/sxhkd.git"
    dest: "{{ temp_dir }}/sxhkd"
  - repo: "https://github.com/baskerville/sutils.git"
    dest: "{{ temp_dir }}/sutils"
  - repo: "https://github.com/baskerville/xtitle.git"
    dest: "{{ temp_dir }}/xtitle"
  - repo: "https://github.com/baskerville/xdo.git"
    dest: "{{ temp_dir }}/xdo"

#
# }}}
# DWM --------------------------------------------------------- {{{
dwm_git:
  - repo: "https://github.com/sunilRF9/Custom-DWM-Build"
    dest: "{{ temp_dir }}/dwm"

#
# }}}

lua_version: "{{ _install_programming.lua.lua_version }}"
