---
__dep_asdf_pkgs:
  - dirmngr
  - gpg
  - curl
  - gawk

__dep_python2_pkgs: []

__dep_python3_pkgs:
  - build-essential
  - git
  - make
  - g++
  - gcc
  - cmake
  - make
  - libssl-dev
  - zlib1g-dev
  - libbz2-dev
  - libreadline-dev
  - libsqlite3-dev
  - llvm
  - libncursesw5-dev
  - xz-utils
  - tk-dev
  - libxml2-dev
  - libxmlsec1-dev
  - libffi-dev
  - liblzma-dev
  - curl
  - wget

__dep_nodejs_pkgs:
  - gpg
  - curl
  - dirmngr
  - gawk

__dep_lua_pkgs:
  - unzip

__dep_ruby_pkgs:
  - autoconf
  - patch
  - build-essential
  - libssl-dev
  - libyaml-dev
  - libreadline6-dev
  - zlib1g-dev
  - libgmp-dev
  - libncurses5-dev
  - libffi-dev
  - libgdbm6
  - libgdbm-dev
  - libdb-dev
  - uuid-dev
