#>> accounts.yml ==============================================================
__pam_auth_file: /etc/pam.d/system-auth
__pam_password_file: /etc/pam.d/password-auth

#>> auth.yml ==================================================================
__pam_postlogin_file: /etc/pam.d/postlogin
