---
- name: TERMINAL-ALACRITTY | Check alacritty path if exists
  ansible.builtin.stat:
    path: "/home/{{ user_admin }}/.asdf/shims/alacritty"
  register: check_alacritty_path
  tags:
    - terminal
    - alacritty

- name: Run if alacritty path not exists
  when: not check_alacritty_path.stat.exists
  tags:
    - terminal
    - alacritty
  block:
    - name: TERMINAL-ALACRITTY | Install alacritty deps
      ansible.builtin.include_role:
        name: _0package
      vars:
        _apt_packages: "{{ __alacritty_pkg }}"

    - name: TERMINAL-ALACRITTY | Install alacritty with cargo
      become: true
      become_user: "{{ user_admin }}"
      changed_when: false
      ansible.builtin.shell: |
        source ~/.asdf/asdf.sh && cargo install alacritty
      args:
        executable: /bin/bash
      register: installed_alacritty

    - name: TERMINAL-ALACRITTY | Reshim rust after install alacritty
      become: true
      become_user: "{{ user_admin }}"
      changed_when: false
      ansible.builtin.shell: |
        source ~/.asdf/asdf.sh && asdf reshim rust
      args:
        executable: /bin/bash
      when: installed_alacritty is success
