---
- name: DOTFILES | Ensure minimal pkg's exists
  ansible.builtin.include_role:
    name: _0package
  vars:
    _apt_packages: ["git", "stow", "vim", "rsync"]
  tags:
    - install

- name: DOTFILES | Git clone my dotfiles from github
  become: true
  become_user: "{{ user_admin }}"
  ansible.builtin.git:
    repo: "https://github.com/mrowegawd/dotfiles.git"
    dest: "/home/{{ user_admin }}/moxconf/development/dotfiles"
    version: "test-plugin"
  changed_when: false
  tags:
    - install
    - programming
    - asdf

- name: DOTFILES | Install the dotfiles
  become: true
  become_user: "{{ user_admin }}"
  ansible.builtin.shell: |
    ./install.sh
  args:
    warn: no
    chdir: "/home/{{ user_admin }}/moxconf/development/dotfiles"
    executable: /bin/bash
  changed_when: false
  tags:
    - always
