---
- name: CONFIG-SSH-QEMU | Configuring ssh to allow root logins
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: PermitRootLogin yes
  notify: restart ssh
  become: true
  tags:
    - qemu
