---
- name: CONFIG-KVM-QEMU | Load all groups
  getent:
    database: group
    split: ":"
  check_mode: false
  tags:
    - qemu

- name: CONFIG-KVM-QEMU | Set unix_sock_group
  set_fact:
    kvm_unix_sock_group: "{{ ('libvirtd' in getent_group) | ternary('libvirtd', 'libvirt') }}"
  when:
    - getent_group is defined
    - "'libvirt' in getent_group or 'libvirtd' in getent_group"
  tags:
    - qemu

# Bagian step ini sampai step ke bawah, ini belum ditest karena belum mengetahui
# arti ansible_check_mode nya, jika sudah tahu artinya, add kembali dengan
# cara uncomment `tags - qemu` nya
- name: CONFIG-KVM-QEMU | Configuring kvm
  template:
    src: etc/libvirt/libvirtd.conf.j2
    dest: /etc/libvirt/libvirtd.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true
  notify: "restart {{ kvm_service_name }}"
  when: not ansible_check_mode
  # tags:
  #   - qemu

- name: CONFIG-KVM-QEMU | Configuring kvm
  replace:
    dest: /etc/default/libvirt-bin
    regexp: '^libvirtd_opts="-d"'
    replace: 'libvirtd_opts="-d -l"'
  become: true
  notify: "restart {{ kvm_service_name }}"
  when:
    - kvm_enable_tcp
    - ansible_os_family == "Debian"
    - not ansible_check_mode
  # tags:
  #   - qemu

- name: CONFIG-KVM-QEMU | Configuring Qemu
  template:
    src: etc/libvirt/qemu.conf.j2
    dest: /etc/libvirt/qemu.conf
    owner: root
    group: root
    mode: u=rw,g=,o=
  become: true
  notify: "restart {{ kvm_service_name }}"
  when:
    - ansible_os_family == "Debian"
    - not ansible_check_mode
  # tags:
  #   - qemu
