---
- name: HW-VIRTUALIZATION-CHECK-QEMU | Load cpu info
  become: true
  ansible.builtin.slurp:
    src: /proc/cpuinfo
  register: cpu_info
  tags:
    - qemu

- name: HW-VIRTUALIZATION-CHECK-QEMU | Idenitfy hw virtualization support
  ansible.builtin.set_fact:
    kvm_domain_type: "{{ cpu_info['content'] | b64decode | regex_search('(vmx|svm)', multiline=True) | ternary('kvm', 'qemu') }}"
  tags:
    - qemu
