---
- name: REDHAT-QEMU-UNDER-VERSION 8 | Installing KVM
  yum:
    name: "{{ kvm_redhat_packages }}"
    state: present
  become: true
  register: result
  until: result is successful
  when: >
    (ansible_distribution == "Fedora" and
    ansible_distribution_major_version <= '12') or
    (ansible_distribution == "CentOS" and
    ansible_distribution_major_version > '8') or
    (ansible_distribution == "RedHat" and
    ansible_distribution_major_version > '8')
  tags:
    - qemu

- name: REDHAT-QEMU-VERSION 8 | Installing KVM
  yum:
    name: "{{ kvm_redhat_8_packages }}"
    state: present
  become: true
  register: result
  until: result is successful
  when: >
    (ansible_distribution == "CentOS" and
    ansible_distribution_major_version == '8') or
    (ansible_distribution == "RedHat" and
    ansible_distribution_major_version == '8')
  tags:
    - qemu

- name: REDHAT-QEMU | Creating libvirt Group
  ansible.builtin.group:
    name: libvirt
    state: present
  become: true
  when: >
    (ansible_distribution == "Fedora" and
    ansible_distribution_major_version <= '12') or
    (ansible_distribution == "CentOS" and
    ansible_distribution_major_version <= '6') or
    (ansible_distribution == "RedHat" and
    ansible_distribution_major_version <= '6')
  tags:
    - qemu

- name: REDHAT-QEMU | Ensuring libvirtd Service Is Enabled and Started
  become: true
  ansible.builtin.service:
    name: libvirtd
    enabled: true
    state: started
  tags:
    - qemu
