---
- name: Converge
  hosts: all
  tasks:
    - name: "Before running set-variables"
      ansible.builtin.include_role:
        name: "set-variables"
    - name: "Converge dunst"
      ansible.builtin.include_role:
        name: "wm-dunst"
