---
- name: PROLANG | Include vars for specific os
  include_vars: "{{ ansible_distribution | lower }}/main.yml"
  tags:
    - always

- become: True
  block:
    - import_tasks: asdf.yml

    - name: Install programming language [prolang]
      include_role:
        name: _0package
        tasks_from: buildasdf
      with_items: "{{ install_prolangs }}"
