---
polybar_version: 3.5.7
polybar_download:
  - url: "https://github.com/polybar/polybar/releases/download/{{ polybar_version }}/polybar-{{ polybar_version }}.tar.gz"
    dest: "{{ temp_dir }}/polybar"
    name: "polybar-{{ polybar_version }}"
