---
polybar_version: 3.7.1
polybar_download:
  - url: "https://github.com/polybar/polybar/releases/download/{{ polybar_version }}/polybar-{{ polybar_version }}.tar.gz"
    dest: "{{ temp_dir_polybar.path }}"
    name: "polybar-{{ polybar_version }}"
