---
- name: Converge for tool-fzf
  hosts: all
  tasks:
    - name: "Before running set-variables"
      ansible.builtin.include_role:
        name: "set-variables"
    - name: "Converge tool-fzf"
      ansible.builtin.include_role:
        name: "tool-fzf"
