---
__deps_pamixer:
  - cmake
  - g++
  - gcc
  - libpulse-dev
  - make
  - meson
  - ninja-build
  - pkg-config
  - uthash-dev

__tools_base_pkg:
  - build-essential
  - git
  - make
  - g++
  - gcc
  - cmake

__tools:
  # basic
  - ccze
  - cmatrix
  - dos2unix
  - expect
  - feh
  - git
  - grc # color output fzf
  - gzip
  - htop
  - jq
  - lxappearance
  - multitail
  - p7zip-full
  - pdfgrep
  - pv
  - rsync
  - snapd
  - stow
  - sxiv # tool for show image or gif
  - task-spooler # task spooler
  - tree
  - unrar
  - unzip
  - vim
  - whois
  - xz-utils # extract tar ext .xz

  # music
  - mpc
  - ncmpcpp
  - mpd
  - vlc

  # video and screen
  - simplescreenrecorder # recording
  - flameshot
  - screenkey
  - vlc
  - scrot # screenshot

  # keyboard viewer
  - screenkey

  # todo manager (not use anymore use orgmode instead)
  # - taskwarrior
  # - remind
  # - incron

  # fancy
  - figlet
  - toilet

  # pdf
  - zathura

  # file manager
  - ranger
  - ffmpegthumbnailer
  - caca-utils
  - highlight
  - atool
  - w3m
  - poppler-utils
  - mediainfo
  - nautilus

  # drawing monitor
  - gromit-mpx

__tools_extensions:
  # zahtura
  - zathura-cb
  - zathura-djvu
  - zathura-pdf-poppler
  - zathura-ps

__tools_from_snapd: []

# tools yang di install melalui ppa
__tools_ppa_keys: []

__tools_ppa: []
#
# }}}
