---
__wm_i3lock_color_deps:
  - autoconf
  - gcc
  - libcairo2-dev
  - libev-dev
  - libfontconfig1-dev
  - libgif-dev
  - libjpeg-dev
  - libpam0g-dev
  - libx11-xcb-dev
  - libxcb-composite0-dev
  - libxcb-image0-dev
  - libxcb-randr0-dev
  - libxcb-util-dev
  - libxcb-xinerama0-dev
  - libxcb-xkb-dev
  - libxcb-xrm-dev
  - libxkbcommon-dev
  - libxkbcommon-x11-dev
  - make
  - pkg-config

__wm_betterlockscreen_deps:
  - x11-utils
  - imagemagick
  - feh
